# Generated by Django 2.1.5 on 2019-02-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Ingrediente')),
                ('value', models.FloatField(null=True, verbose_name='Valor do Ingrediente')),
                ('category', models.IntegerField(null=True, verbose_name='Categoria do ingrediente 1-Alface | 2-Bacon | 3-Hambúrguer de carne | 4-Ovo | 5-Queijo')),
            ],
        ),
        migrations.CreateModel(
            name='SoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snack', models.CharField(max_length=255, verbose_name='Nome do Ingrediente')),
                ('img_snack', models.CharField(max_length=255, verbose_name='foto do lanche')),
                ('amount_lettuce', models.IntegerField(verbose_name='Quantidade de alface')),
                ('amount_bacon', models.IntegerField(verbose_name='Quantidade de Bacon')),
                ('amount_burger', models.IntegerField(verbose_name='Quantidade de Hambúguer de carne')),
                ('amount_egg', models.IntegerField(verbose_name='Quantidade de ovo')),
                ('amount_cheese', models.IntegerField(verbose_name='Quantidade de queijo')),
                ('price', models.FloatField(null=True, verbose_name='Valor do lanche')),
                ('is_buy', models.BooleanField(default=False, verbose_name='True - Lanche comprado, False - No carrinho.')),
            ],
        ),
    ]
