# Generated by Django 2.1.5 on 2019-02-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Ingrediente')),
                ('value', models.FloatField(null=True, verbose_name='Valor do lanche')),
                ('category', models.IntegerField(null=True, verbose_name='Categoria do ingrediente 1-Alface | 2-Bacon | 3-Hambúrguer de carne | 4-Ovo | 5-Queijo')),
            ],
        ),
    ]
