# Generated by Django 2.1.5 on 2019-02-07 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snackbar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
