# Generated by Django 2.1.5 on 2019-02-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snackbar', '0002_auto_20190207_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_snack', models.CharField(max_length=255, verbose_name='Nome do Ingrediente')),
                ('img_snack', models.CharField(max_length=255, verbose_name='foto do lanche')),
                ('amount_lettuce', models.IntegerField(verbose_name='Quantidade de alface')),
                ('amount_bacon', models.IntegerField(verbose_name='Quantidade de Bacon')),
                ('amount_burger', models.IntegerField(verbose_name='Quantidade de Hambúguer de carne')),
                ('amount_egg', models.IntegerField(verbose_name='Quantidade de ovo')),
                ('amount_cheese', models.IntegerField(verbose_name='Quantidade de queijo')),
            ],
        ),
    ]
