# Generated by Django 2.1.5 on 2019-02-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snackbar', '0004_auto_20190208_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='soppingcart',
            name='is_buy',
            field=models.BooleanField(default=False, verbose_name='True - Lanche comprado, False - No carrinho.'),
        ),
    ]
